### PR TITLE
editor: restore default value for hidden field

### PR DESCRIPTION
**Pull request by jma**
* Updates JSONSchema to add default values for the editor.
* Changes the way to hide a field in the editor.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Why are you opening this PR?

- To fix: rero/rero-ils#1119.

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/ng-core#291

## How to test?

- Create a new document record. Fill optional fields, hide/show the default value should be there and the value should be the same as after the form creation.
- The editor should be tested for the document, the holding, the item and the templates.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

### CODE REVIEW

**Review by lauren-d — APPROVED** [review]

**Review by BadrAly — APPROVED** [review]

**Review by pronguen — COMMENTED** [review]
- [ ] When I have various `contribution` and I remove one, it reset the values of the others (except the role).
- [ ] If possible, when I add a `provisionActivity`, I should have the following fields and default values:

image

- [ ] In the item editor, the mention "New acquisition" above the date field went lost. This is already the case in v0.13.0.

image

Maybe not related to this PR:

- [ ] When I edit this [document](https://ilsdev.test.rero.ch/professional/records/documents/edit/1201) and just modify a caracter, I cannot save. Fields have been added.

**Comment by benerken** [comment]
1/ Import BNF (may be not linked to the editor ?)
I have imported one record from BNF without problem. Then, I try to import another one.
When I save this second document, I get an error 500 in my console and the spinner loops...

image


2/ FYI : **It's not a blocking issue** 
when I try to import a document from BNF (ex: https://ilsdev.test.rero.ch/professional/records/documents/new?source=bnf&pid=FRBNF455770370000004) , the editor displays duplicate entries/links on the left of the screen.
It's not the case with a new document (from scratch) or the edition of an existing document. 

image

**Comment by benerken** [comment]
1/ **Not a blocking issue**
When I try to import a document from BNF (ex: https://ilsdev.test.rero.ch/professional/records/documents/new?source=bnf&pid=FRBNF39904997000000X) , several entries on the left are duplicated.... 

image


2/ I can import one document from BNF. But when I try to import another record, I get an error 400 in my console and the spinner loops.

image

**Comment by JoelleDosimont** [comment]
- The editor seems to have some difficulties when there are two proper titles (for ex. with non roman scripture). It spins forever : 
image
Same for the notes. It saves if there is only one note. 
- On Firefox, when I delete the ISBN identifiers with a value and add it again, the value is retained. On chrome, the value is missing. If I refresh the page, the value comes back. 
- Sometimes, when deleting the “Place” and adding it back, the default values are not present (and it’s impossible to add them manually) : 
image
Not sure it's directly linked to this PR : 
- Adding the "Extent" field, it appears under the permanent "save" header. 
- In the item (or issue item) barcode is mandatory but sometimes, there is no barcode (item create for acquisition for example). Before, a temporary barcode was created.

**Comment by jma** [comment]
All the reported issues should be solved. But three of them:

> When I edit this document and just modify a caracter, I cannot save. Fields have been added.
This need to be an issue: in edit mode all optional field without value should be hidden in the document editor.

>Adding the "Extent" field, it appears under the permanent "save" header.
This need to be an issue.

>If possible, when I add a provisionActivity, I should have the following fields and default values.
The following ngx-formly can solve this issue: https://github.com/ngx-formly/ngx-formly/issues/2569

**Pull request merged**
