### PR TITLE
Add claim mechanism for periodical issues

### PR DESCRIPTION
**Pull request by PascalRepond**
## Why are you opening this PR?

- Taiga US https://tree.taiga.io/project/rero21-reroils/us/2509

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* https://github.com/rero/rero-ils-ui/pull/990

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

### CODE REVIEW

**Review by Garfield-fr — COMMENTED** [review]
Rebase to have 1 commit ?

**Comment by PascalRepond** [comment]
@Garfield-fr This is a feature branch with 6 commits umerged to staging. I don't think rebasing will lower the number of commits, right?

**Comment by Garfield-fr** [comment]
> @Garfield-fr This is a feature branch with 6 commits umerged to staging. I don't think rebasing will lower the number of commits, right?

@PascalRepond You need to rebase the 'US-2509-claim' branch to have just one commit. That would be nice because it's a feature. But you can also merge like this

**Comment by PascalRepond** [comment]
> @PascalRepond You need to rebase the 'US-2509-claim' branch to have just one commit. That would be nice because it's a feature. But you can also merge like this

We don't usually sqash commits from a feature branch, why change? (recent examples: https://github.com/rero/rero-ils/pull/3247, https://github.com/rero/rero-ils/pull/3185)

**Comment by Garfield-fr** [comment]
@PascalRepond For me, to have a clean history, we should have 1 commit per feature. But that's just my opinion. I'll validate...

**Review by Garfield-fr — APPROVED** [review]

**Pull request merged**
