### PR TITLE
Implement stats for pricing

### PR DESCRIPTION
**Pull request by jma**
## Why are you opening this PR?

- https://tree.taiga.io/project/rero21-reroils/us/1848?milestone=294722

## How to test?

- logged in as admin@rero.ch
- go to the tools menu and select statistics
- explore the interface
- try to modify the data (loans, documents, etc.) go to the live view and see that the values are changed.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

### CODE REVIEW

**Comment by iGormilhit** [comment]
[not blocking] It could be useful to have the time span of the collected data in the CSV file.

**Review by iGormilhit — APPROVED** [review]

**Review by benerken — APPROVED** [review]

**Comment by mmo** [comment]
It could be useful to use the timestamp as file name, eg. `2021-07-02 09-43-26.493774.csv` . But it's a detail.

**Review by mmo — APPROVED** [review]

**Comment by jma** [comment]
> [not blocking] It could be useful to have the time span of the collected data in the CSV file.

as proposed by Miguel the time stamp will be in the file name.

**Comment by jma** [comment]
> It could be useful to use the timestamp as file name, eg. `2021-07-02 09-43-26.493774.csv` . But it's a detail.

Done

**Pull request merged**
