### PR TITLE
frontend: translations

### PR DESCRIPTION
**Pull request by iGormilhit**
* NEW: translates the sprint 11 features

Signed-off-by: Igor Milhit <igor.milhit@rero.ch>

### CODE REVIEW

**Comment by iGormilhit** [comment]
@BadrAly Is it a translation issue, or a coding issue? The name of the module is `Persons` and the resource type is `pers`. According to [US 602](https://tree.taiga.io/project/rero21-reroils/us/602), I think it should be `persons`.

@rerowep and @BadrAly But the issue is, that it the same string that's translated and displayed at several places: the admin menu, but also the type of the author of a document (person or organisation), and sometimes it should be plural, others singular. Transifex says:

```
Occurences:
rero_ils/modules/documents/form_options/documents/document-v0.0.1.json:108, rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html:10 
```

**Comment by rerowep** [comment]
> @rerowep and @BadrAly But the issue is, that it the same string that's translated and displayed at several places: the admin menu, but also the type of the author of a document (person or organisation), and sometimes it should be plural, others singular. Transifex says:
> 
> ```
> Occurences:
> rero_ils/modules/documents/form_options/documents/document-v0.0.1.json:108, rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html:10 
> ```

Yes, but why the french and english is in plural and german in singular ?

**Comment by iGormilhit** [comment]
@rerowep Because you proposed this translations in transifex: https://www.transifex.com/rero/reroils/translate/#de/$/154056376?q=text%3A%22pers%22 :smile:

**Comment by rerowep** [comment]
@iGormilhit Ok I have changed it in transiflex ...

**Comment by BadrAly** [comment]
> @BadrAly Is it a translation issue, or a coding issue? The name of the module is `Persons` and the resource type is `pers`. According to [US 602](https://tree.taiga.io/project/rero21-reroils/us/602), I think it should be `persons`.
> 
> @rerowep and @BadrAly But the issue is, that it the same string that's translated and displayed at several places: the admin menu, but also the type of the author of a document (person or organisation), and sometimes it should be plural, others singular. Transifex says:
> 
> ```
> Occurences:
> rero_ils/modules/documents/form_options/documents/document-v0.0.1.json:108, rero_ils/modules/persons/templates/rero_ils/detailed_view_persons.html:10 
> ```

**Comment by BadrAly** [comment]
I pushed a button here by mistake .. do not know which

**Comment by iGormilhit** [comment]
@rerowep Thanks for the changes in Transifex. I've updated my PR with your changes.

**Pull request merged**
