### PR TITLE
holdings: attach serials to non-serials documents

### LINKED ISSUE #1612: Serial holdings should be allowed on any document types
**How it works**

Currently, serial holdings can only be added to document of type "Journal". This is a problem for the editorial collections, comics series, etc., that have holdings rather than items.

**Improvement suggestion**

* On the document detailed view, I have a button "Add holdings"
   * I can choose to add a standard, serial or online type.
* If I choose "standard", we can imagine having the item editor visually separated in two spaces, one for the holdings, one for the item.

### PR DESCRIPTION
**Pull request by BadrAly**
* Allows to:
        * Attach holdings of serial type to any type of document.
        * Attach holdings of standard type to document of type journal.
        * Attach items of standard type to holdings of type serial.
* Closes #1612

Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Why are you opening this PR?

https://tree.taiga.io/project/rero21-reroils/task/1883?kanban-status=1224895

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

### CODE REVIEW

**Comment by zannkukai** [comment]
maybe we need to talk about this in a daily meeting. It seems that allows to create a big "holdings salad" with potential problem into the UI

**Review by iGormilhit — COMMENTED** [review]
I don't understand the notion of "loading holdings on document". But as we're gonna discuss this at the daily meeting...

**Review by jma — COMMENTED** [review]
Tests are missing. Perhaps later?

**Comment by BadrAly** [comment]
This PR is on hold, need a discussion on how to best load the pilot documents/holdings/items.
solution for version `14`is to force the document type to `journal`.

**Review by iGormilhit — CHANGES_REQUESTED** [review]
Commit message proposition:

```
holdings: attach serials to non-serials documents

* Allows to:
    * Attach holdings of serial type to any type of document.
    * Attach holdings of standard type to document of type journal.
    * Attach items of standard type to holdings of type serial.
* Closes #1612.
```

**Review by Garfield-fr — APPROVED** [review]

**Review by rerowep — APPROVED** [review]

**Review by iGormilhit — APPROVED** [review]

**Pull request merged**
